### Get all channels

GET {{BaseUrl}}/channels
Accept: application/json

### Get channel

GET {{BaseUrl}}/channels/PoorBishopHooper
Accept: application/json

### Get channel videos

GET {{BaseUrl}}/channels/PoorBishopHooper/videos
Accept: application/json
