### Ignore video
PUT {{BaseUrl}}/videos/ignored
Content-Type: application/json

{
  "videoId": "-JIpItvRfv4"
}

### Download video
PUT {{BaseUrl}}/videos/downloaded
Content-Type: application/json

{
  "videoId": "-JIpItvRfv4"
}
