### Ignore video
PUT {{BaseUrl}}/videos/ignored
Content-Type: application/json

{
  "videoId": "-JIpItvRfv4"
}

### Download video
PUT {{BaseUrl}}/videos/downloaded
Content-Type: application/json

{
  "videoId": "-JIpItvRfv4"
}

### Get video info
GET {{BaseUrl}}/videos/4vY-wPL7fVs

### Get video stream
GET {{BaseUrl}}/videos/4vY-wPL7fVs/streams/webm
