// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SimpleTube.RestApi.Infrastructure.Database.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SimpleTube.RestApi.Infrastructure.Database.Compiled
{
    public static class AuditableEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(AuditableEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastModifiedAt>k__BackingField")]
        public static extern ref DateTimeOffset LastModifiedAt(AuditableEntity @this);
    }
}
