// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SimpleTube.RestApi.Infrastructure.Database.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SimpleTube.RestApi.Infrastructure.Database.Compiled
{
    public static class ChannelEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref string Id(ChannelEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Handle>k__BackingField")]
        public static extern ref string Handle(ChannelEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(ChannelEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Thumbnail>k__BackingField")]
        public static extern ref string Thumbnail(ChannelEntity @this);
    }
}
