// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SimpleTube.RestApi.Infrastructure.Database.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SimpleTube.RestApi.Infrastructure.Database.Compiled
{
    public static class SubscriptionEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref string ChannelId(SubscriptionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelHandle>k__BackingField")]
        public static extern ref string ChannelHandle(SubscriptionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelName>k__BackingField")]
        public static extern ref string ChannelName(SubscriptionEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelThumbnail>k__BackingField")]
        public static extern ref string ChannelThumbnail(SubscriptionEntity @this);
    }
}
