// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using SimpleTube.RestApi.Infrastructure.Database.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SimpleTube.RestApi.Infrastructure.Database.Compiled
{
    public static class VideoEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref string Id(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref string ChannelId(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Duration>k__BackingField")]
        public static extern ref TimeSpan Duration(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ETag>k__BackingField")]
        public static extern ref string ETag(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PublishedAt>k__BackingField")]
        public static extern ref DateTime PublishedAt(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Thumbnail>k__BackingField")]
        public static extern ref string Thumbnail(VideoEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(VideoEntity @this);
    }
}
